<?php

return [
  'video' => [
    [
      'thumbnail' => 'https://i.ytimg.com/vi/ogv284C4W30/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDkK7m_YTARlyw6owRb8w3mDQlexA',
      'profile-picture' => 'https://yt3.ggpht.com/a/AATXAJyK1ENIB9XZL3yRNlGCFGtQZnug9E2yytLdCGEbEQ=s88-c-k-c0x00ffffff-no-rj',
      'name' => 'KygoMusic',
      'title' => 'Kygo, Sasha Sloan - I\'ll Wait (Lyric Video)',
      'visual' => '11 Mln di',
      'duration' => '3:44',
      'time' => '4 mesi fa',
    ],
    [
      'thumbnail' => 'https://i.ytimg.com/vi/Qz-Rfh_FXws/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDJpq2X5qP5a7ZtiOFQrOTdyLoX8A',
      'profile-picture' => 'https://yt3.ggpht.com/a-/AOh14GhZT2KiE8uQCYSnpGB_NRZyNp4LdfsGBfQE0A=s68-c-k-c0x00ffffff-no-rj-mo',
      'title' => 'THE BEST OF ALBERTO BIGIOGGERO',
      'name' => 'Arthur Fleck',
      'visual' => '236.118',
      'duration' => '6:01',
      'time' => '1 mese fa',
    ],
    [
      'thumbnail' => 'https://i.ytimg.com/vi/8POA9lIcHjE/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAS-IY3MezEkczBi58iinUHFeGYJQ',
      'profile-picture' => 'https://yt3.ggpht.com/a-/AOh14GilT2Vs5Qzio4vEXwO8gh7ppL7RH_qgkqk5tA=s68-c-k-c0x00ffffff-no-rj-mo',
      'title' => '1 meme from every episode of JoJo\'s Bizarre Adventure',
      'name' => 'The Shuckmeister',
      'visual' => '4.619.925',
      'duration' => '14:47',
      'time' => '7 mesi fa',
    ],
    [
      'thumbnail' => 'https://i.ytimg.com/vi/Ywq6FMLbWH4/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDHX3XfbnIC2zvB2LDBYmNKris4lw',
      'profile-picture' => 'https://yt3.ggpht.com/a-/AOh14GhJ1DhEqfMxAR8pV5J8UqlhCBcBDhSlabhxEQ=s68-c-k-c0x00ffffff-no-rj-mo',
      'title' => 'Hippie Sabotage - Devil Eyes',
      'name' => 'CloudKid',
      'visual' => '175 Mln di',
      'duration' => '3:52',
      'time' => '1 anno fa',
    ],
    [
      'thumbnail' => 'https://i.ytimg.com/vi/G1IbRujko-A/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBvRzV54b4k59RyQ50RMUeThdsTXQ',
      'profile-picture' => 'https://yt3.ggpht.com/a-/AOh14GgbIq4GwkbFf-ZB2i4spg9eS_ghiRURN8RBxA=s68-c-k-c0x00ffffff-no-rj-mo',
      'title' => 'Gandalf Sax Guy 10 Hours HD',
      'name' => '10 Hours',
      'visual' => '17 Mln di',
      'duration' => '10:00:37',
      'time' => '3 anni fa',
    ],
    [
      'thumbnail' => 'https://i.ytimg.com/vi/uD4izuDMUQA/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBtFDmnGE1q7uayAJQ5ZFm0yEiJZw',
      'profile-picture' => 'https://yt3.ggpht.com/a-/AOh14GieZHILbVUXTh676THKOR-TKFxIuiFvgq_xUA=s68-c-k-c0x00ffffff-no-rj-mo',
      'title' => 'TIMELAPSE DEL FUTURO: Un Viaggio alla Fine del Tempo (4K)',
      'name' => 'melodysheep',
      'visual' => '40 Mln di',
      'duration' => '29:21',
      'time' => '1 anno fa',
    ],
    [
      'thumbnail' => 'https://i.ytimg.com/vi/X2MbVu5_tV4/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDe-gvHmevgkjCEU3O3gsmbpvnS9g',
      'profile-picture' => 'https://yt3.ggpht.com/a-/AOh14Ggfo4nclYKud810BD2KiTZ9Lh_cQz3ZoH5byg=s68-c-k-c0x00ffffff-no-rj-mo',
      'title' => 'PRIMO ATTACCO',
      'name' => 'domenico bini',
      'visual' => '7772',
      'duration' => '3:06',
      'time' => '1 giorno fa',
    ],
    [
      'thumbnail' => 'https://i.ytimg.com/vi/waapP8AIi-Q/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLD3ToQnM1v0xH1y9G64stnWvpa3hg',
      'profile-picture' => 'https://yt3.ggpht.com/a-/AOh14Gi-0QYgry3Zy2aXN3A81PMzrU_n5D4tyOrTww=s68-c-k-c0x00ffffff-no-rj-mo',
      'title' => 'Quello che NON volevi sapere sul panda - SCIENZA BRUTTA',
      'name' => 'Barbascura X',
      'visual' => '1,4 Mln di',
      'duration' => '17:02',
      'time' => '2 anni fa',
    ],
    [
      'thumbnail' => 'https://i.ytimg.com/vi/hVl6LvwYdEU/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAGklLu6y851YrDFbOCfO1sfDlCpQ',
      'profile-picture' => 'https://yt3.ggpht.com/a-/AOh14GjipsCJ4Ec_dMpQOdZLYL_GVJDGx6fEFjC-vA=s68-c-k-c0x00ffffff-no-rj-mo',
      'title' => 'RECENSIONE FILM - AlbaKiara',
      'name' => 'yotobi',
      'visual' => '3,6 Mln di',
      'duration' => '20:14',
      'time' => '7 anni fa',
    ],
    [
      'thumbnail' => 'https://i.ytimg.com/vi/zOy6pdGXVxQ/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLA5TaT2FzWSPQJBkYZqkcGuSB24PA',
      'profile-picture' => 'https://yt3.ggpht.com/a-/AOh14GhrO4YKJBgEU0DXetmlgJROg7zRSecxpmxBdw=s68-c-k-c0x00ffffff-no-rj-mo',
      'title' => 'IL KING DELLE BESTEMMIE 6 [66] - L\'ANTICRISTO E\' TORNATO. (SPECIALE 100K #2)',
      'name' => 'StallionsTV / SoaR Blur!',
      'visual' => '4,3 Mln di',
      'duration' => '12:59',
      'time' => '4 anni fa',
    ],
    [
      'thumbnail' => 'https://i.ytimg.com/vi/7I6upzR9xjc/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBGv6Z4LHfuJsMYUCATfNMscCXWxg',
      'profile-picture' => 'https://yt3.ggpht.com/a/AATXAJyGVPwS34VI5i0yYhA1Zzmvu7dEOqsbv-wWR0__4w=s88-c-k-c0xffffffff-no-rj-mo',
      'name' => 'Jumbodrillo',
      'title' => 'Ecco perchè giro con un coltello',
      'visual' => '793.648',
      'duration' => '11:14',
      'time' => '1 anno fa',
    ],
    [
      'thumbnail' => 'https://i.ytimg.com/vi/dFSuW7GEF5U/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAbIKxfu1hm2_FNi5jU87cdCaNeKg',
      'profile-picture' => 'https://yt3.ggpht.com/a/AATXAJwBiX5zvMKMzlBXxlbemotXh0twg9F2pu7-CJKL=s48-c-k-c0xffffffff-no-rj-mo',
      'title' => 'Goku Super Saiyan vs Freezer-It\'s My Life',
      'name' => 'javiernm31',
      'visual' => '380.258',
      'duration' => '3:51',
      'time' => '10 anni fa',
    ],
  ]
];
