<?php

return [
  'video' => [
    [
      'thumbnail' => 'https://i.ytimg.com/vi/ogv284C4W30/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDkK7m_YTARlyw6owRb8w3mDQlexA',
      'profile-picture' => 'https://yt3.ggpht.com/a/AATXAJyK1ENIB9XZL3yRNlGCFGtQZnug9E2yytLdCGEbEQ=s88-c-k-c0x00ffffff-no-rj',
      'name' => 'KygoMusic',
      'title' => 'Kygo, Sasha Sloan - I\'ll Wait (Lyric Video)',
      'visual' => '11 Mln di',
      'duration' => '3:44',
      'time' => '4 mesi fa',
    ],
    [
      'thumbnail' => 'https://i.ytimg.com/vi/Qz-Rfh_FXws/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDJpq2X5qP5a7ZtiOFQrOTdyLoX8A',
      'profile-picture' => 'https://yt3.ggpht.com/a-/AOh14GhZT2KiE8uQCYSnpGB_NRZyNp4LdfsGBfQE0A=s68-c-k-c0x00ffffff-no-rj-mo',
      'title' => 'THE BEST OF ALBERTO BIGIOGGERO',
      'name' => 'Arthur Fleck',
      'visual' => '236.118',
      'duration' => '6:01',
      'time' => '1 mese fa',
    ],
    [
      'thumbnail' => 'https://i.ytimg.com/vi/8POA9lIcHjE/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAS-IY3MezEkczBi58iinUHFeGYJQ',
      'profile-picture' => 'https://yt3.ggpht.com/a-/AOh14GilT2Vs5Qzio4vEXwO8gh7ppL7RH_qgkqk5tA=s68-c-k-c0x00ffffff-no-rj-mo',
      'title' => '1 meme from every episode of JoJo\'s Bizarre Adventure',
      'name' => 'The Shuckmeister',
      'visual' => '4.619.925',
      'duration' => '14:47',
      'time' => '7 mesi fa',
    ],
    [
      'thumbnail' => 'https://i.ytimg.com/vi/Ywq6FMLbWH4/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDHX3XfbnIC2zvB2LDBYmNKris4lw',
      'profile-picture' => 'https://yt3.ggpht.com/a-/AOh14GhJ1DhEqfMxAR8pV5J8UqlhCBcBDhSlabhxEQ=s68-c-k-c0x00ffffff-no-rj-mo',
      'title' => 'Hippie Sabotage - Devil Eyes',
      'name' => 'CloudKid',
      'visual' => '175 Mln di',
      'duration' => '3:52',
      'time' => '1 anno fa',
    ],
    [
      'thumbnail' => 'https://i.ytimg.com/vi/G1IbRujko-A/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBvRzV54b4k59RyQ50RMUeThdsTXQ',
      'profile-picture' => 'https://yt3.ggpht.com/a-/AOh14GgbIq4GwkbFf-ZB2i4spg9eS_ghiRURN8RBxA=s68-c-k-c0x00ffffff-no-rj-mo',
      'title' => 'Gandalf Sax Guy 10 Hours HD',
      'name' => '10 Hours',
      'visual' => '17 Mln di',
      'duration' => '10:00:37',
      'time' => '3 anni fa',
    ],
    [
      'thumbnail' => '',
      'profile-picture' => '',
      'title' => '',
      'name' => '',
      'visual' => '',
      'duration' => '',
      'time' => '',
    ],
    [
      'thumbnail' => '',
      'profile-picture' => '',
      'title' => '',
      'name' => '',
      'visual' => '',
      'duration' => '',
      'time' => '',
    ],
    [
      'thumbnail' => '',
      'profile-picture' => '',
      'title' => '',
      'name' => '',
      'visual' => '',
      'duration' => '',
      'time' => '',
    ],
    [
      'thumbnail' => '',
      'profile-picture' => '',
      'title' => '',
      'name' => '',
      'visual' => '',
      'duration' => '',
      'time' => '',
    ],
    [
      'thumbnail' => '',
      'profile-picture' => '',
      'title' => '',
      'name' => '',
      'visual' => '',
      'duration' => '',
      'time' => '',
    ],
    [
      'thumbnail' => '',
      'profile-picture' => '',
      'title' => '',
      'name' => '',
      'visual' => '',
      'duration' => '',
      'time' => '',
    ],
    [
      'thumbnail' => '',
      'profile-picture' => '',
      'title' => '',
      'name' => '',
      'visual' => '',
      'duration' => '',
      'time' => '',
    ],
  ]
];
